installed_at: '2026-03-09T08:35:13+00:00'
skill_id: git/test-skill
git_repo: https://github.com/test/repo
skill_path: /private/var/folders/c2/23jm52w977q_lbyjfb3453hh0000gp/T/tmp8glxqqy_/test-skill
git_sha: local
skilz_version: 1.10.0
install_mode: copy
canonical_path: null
